[package]
name = "gyokuto-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chumsky.workspace = true
logos.workspace = true
thiserror.workspace = true
gyokuto-lexer = { path = "../lexer" }

[dev-dependencies]
rstest.workspace = true
